<?xml version="1.0"?>

<robot xmlns:xacro="http://ros.org/wiki/xacro">
  <xacro:property name="camera_x" value="0.05" />
  <xacro:property name="camera_y" value="0.025" />
  <xacro:property name="camera_z" value="0.08" />
  <xacro:property name="camera_mass" value="1.1" />

  <xacro:macro name="box_inertial" params="x y z mass">
    <inertial>
      <mass value="${mass}" />
      <origin xyz="0 0 0" />
      <inertia ixx="${0.0833333 * mass * (y*y + z*z)}" ixy="0.0" ixz="0.0" 
        iyy="${0.0833333 * mass * (x*x + z*z)}" iyz="0.0" 
        izz="${0.0833333 * mass * (x*x + y*y)}" />
    </inertial>
  </xacro:macro>

  <xacro:macro name="front_camera_mount" params="prefix topic">
    <link name="${prefix}_camera">
      <xacro:box_inertial x="${camera_x}" y="${camera_y}" z="${camera_z}" mass="${camera_mass}" />
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <box size="${camera_x} ${camera_y} ${camera_z}" />
        </geometry>
        <material name="light_grey" />
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <box size="${camera_x} ${camera_y} ${camera_z}" />
        </geometry>
      </collision>
    </link>

    <link name="${prefix}_camera_viewpoint"></link>

    <joint name="${prefix}_camera_joint" type="fixed">
      <!-- This offset is from the base of the bracket to the LIDAR's focal point. -->
      <origin xyz="${camera_x*0.5} 0 ${camera_z*0.5}" rpy="0 0 0" />
      <parent link="${prefix}_camera" />
      <child link="${prefix}_camera_viewpoint" />
    </joint>

    <!-- camera -->
    <gazebo reference="${prefix}_camera_viewpoint">
      <sensor type="camera" name="${prefix}_camera_viewpoint">
        <update_rate>30.0</update_rate>
        <camera name="head">
          <horizontal_fov>1.3962634</horizontal_fov>
          <image>
            <width>800</width>
            <height>600</height>
            <format>R8G8B8</format>
          </image>
          <clip>
            <near>0.02</near>
            <far>300</far>
          </clip>
          <noise>
            <type>gaussian</type>
            <!-- Noise is sampled independently per pixel on each frame.
                 That pixel's noise value is added to each of its color
                 channels, which at that point lie in the range [0,1]. -->
            <mean>0.0</mean>
            <stddev>0.007</stddev>
          </noise>
        </camera>
        <plugin name="camera_controller" filename="libgazebo_ros_camera.so">
          <alwaysOn>true</alwaysOn>
          <updateRate>0.0</updateRate>
          <cameraName>${prefix}_camera</cameraName>
          <imageTopicName>image_raw</imageTopicName>
          <cameraInfoTopicName>camera_info</cameraInfoTopicName>
          <frameName>${prefix}_camera</frameName>
          <hackBaseline>0.07</hackBaseline>
          <distortionK1>0.0</distortionK1>
          <distortionK2>0.0</distortionK2>
          <distortionK3>0.0</distortionK3>
          <distortionT1>0.0</distortionT1>
          <distortionT2>0.0</distortionT2>
        </plugin>
      </sensor>
    </gazebo>
  </xacro:macro>
</robot>
